modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${mod_licence}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="assets/logo.png"
authors="${mod_authors}"
updateJSONURL="https://raw.githubusercontent.com/Toma1O6/UpdateSchemas/refs/heads/master/configuration-forge.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/configuration"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"