import net.darkhax.curseforgegradle.*

buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
}

plugins {
    id 'fabric-loom' version "${fabric_loom}"
    id 'idea'
    id 'maven-publish'
    id 'net.darkhax.curseforgegradle' version "${cursegradle_plugin_version}"
    id 'com.modrinth.minotaur' version "${modrinth_plugin_version}"
}

version = "${project.version}"
group = project.mod_group
def classifier = 'fabric'
base {
    archivesName = "${project.mod_id}-${classifier}-${project.minecraft_version}"
}

repositories {
    maven {
        name = "Terraformers" // Modmenu
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Modmenu
    if (modmenu_runtime.toBoolean()) {
        modImplementation "com.terraformersmc:modmenu:${modmenu_version}"
    } else {
        // since 1.21.9 release is not available yet, use only compile version and pray the API stays the same after release
        modCompileOnly "com.terraformersmc:modmenu:${modmenu_version}"
    }


    compileOnly project(":common")
}

loom {
    def accessWidenerFile = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (accessWidenerFile.exists()) {
        accessWidenerPath.set(accessWidenerFile)
    }

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run/server")
        }
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "${mod_name}",
                "Specification-Vendor"    : "${mod_authors}",
                "Specification-Version"   : project.jar.archiveVersion,
                "Implementation-Title"    : "${mod_name}",
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "${mod_authors}",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    exclude("META-INF/accesstransformer.cfg")
}

processResources {
    from project(":common").sourceSets.main.resources
}

tasks.withType(JavaCompile) {
    source(project(":common").sourceSets.main.allSource)
}

tasks.register('publishToCurseForge', TaskPublishCurseForge) {
    dependsOn(tasks.remapJar)
    apiToken = project.findProperty("CURSEFORGE_TOKEN").toString() ?: ""
    debugMode = debug.toBoolean()

    def uploadFile = upload(curseforge_project_id, tasks.remapJar.archiveFile)
    uploadFile.changelogType = Constants.CHANGELOG_MARKDOWN
    uploadFile.changelog = file("../CHANGELOG.md").exists() ? file('../CHANGELOG.md').text : "-- No changelog provided --"
    uploadFile.releaseType = Constants.RELEASE_TYPE_RELEASE
    uploadFile.displayName = "${mod_id}-fabric-${minecraft_version}-${version}"
    uploadFile.addModLoader('Fabric')
    uploadFile.addEnvironment('Client', 'Server')
    uploadFile.addJavaVersion("Java 21")
    compatible_mc_versions.split(",").each { gameVersion ->
        uploadFile.addGameVersion(gameVersion)
    }
}

List compatibleVersions = compatible_mc_versions.split(",")
modrinth {
    token = project.findProperty("MODRINTH_TOKEN").toString() ?: ""
    projectId = modrinth_project_id
    versionNumber = "${version}"
    versionName = "${mod_id}-fabric-${minecraft_version}-${version}"
    versionType = "release"
    uploadFile = remapJar
    gameVersions = compatibleVersions
    debugMode = debug.toBoolean()
    changelog = file("../CHANGELOG.md").exists() ? file("../CHANGELOG.md").text : "-- No changelog provided --"
    loaders = ["fabric"]
}
tasks.modrinth.dependsOn(tasks.remapJar)

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.group
            artifactId = "${project.mod_id}-${project.minecraft_version}"
            version = "${project.version}-${classifier}"
            from components.java
        }
    }

    repositories {
        maven {
            url = uri(project.findProperty("MAVEN_PUBLIC_URL").toString() ?: "")
            credentials {
                username project.findProperty("MAVEN_USERNAME").toString() ?: ""
                password project.findProperty("MAVEN_PASSWORD").toString() ?: ""
            }
        }
    }
}