plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.4.1"
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    java {
        withSourcesJar()

        toolchain {
            languageVersion = JavaLanguageVersion.of("${java_version}")
        }
    }

    jar {
        manifest {
            attributes([
                    'Specification-Title'       : "${mod_name}",
                    'Specification-Vendor'      : "${mod_authors}",
                    'Specification-Version'     : "${mod_version}",
                    'Implementation-Title'      : "${project.name}",
                    'Implementation-Version'    : "${mod_version}",
                    'Implementation-Vendor'     : "${mod_authors}",
                    'Implementation-Timestamp'  : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    'Timestamp'                 : System.currentTimeMillis()
            ])
        }
    }

    repositories {
        mavenCentral()

        maven {
            name = "Sponge / Mixin"
            url  = "https://repo.spongepowered.org/repository/maven-public/"
        }
    }

    processResources {
        def props = [
                // Mod
                "version": "${mod_version}",
                "mod_id": "${mod_id}",
                "mod_name": "${mod_name}",
                "mod_authors": "${mod_authors}",
                "mod_licence": "${mod_licence}",
                "mod_description": "${mod_description}",
                "mod_group": "${mod_group}",

                // Minecraft env
                "java_version": "${java_version}",
                "minecraft_version": "${minecraft_version}",
                "minecraft_version_range": "${minecraft_version_range}",
                "vanilla_gradle_version": "${vanilla_gradle_version}",

                // Mixin env
                "mixin_loader": "${mixin_loader}",
                "mixin_version": "${mixin_version}",
                "mixin_min_version": "${mixin_min_version}",

                // Neoforge
                "neoforge_version": "${neoforge_version}",
                "neoforge_loader_range": "${neoforge_loader_range}",
                "neoforge_version_range": "${neoforge_version_range}",
                "neogradle_userdev": "${neogradle_userdev}",

                // Fabric
                "fabric_version": "${fabric_version}",
                "fabric_loader_version": "${fabric_loader_version}",
                "fabric_loom": "${fabric_loom}",
                "fabric_mc_version": "${fabric_minecraft_version}"
        ]

        filesMatching(["pack.mcmeta", "fabric.mod.json", "META-INF/*.toml", "*.mixins.json"]) {
            expand(props)
        }
        inputs.properties(props)
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                groupId = project.group
                artifactId = "${project.mod_id}-${project.platform}"
                version = "${project.version}"

                artifact jar
                artifact sourcesJar
            }
        }

        repositories {
            maven {
                url = uri(project.findProperty("MAVEN_PUBLIC_URL").toString() ?: "")
                credentials {
                    username project.findProperty("MAVEN_USERNAME").toString() ?: ""
                    password project.findProperty("MAVEN_PASSWORD").toString() ?: ""
                }
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
        it.options.getRelease().set(project.java_version.toInteger())
    }

    tasks.withType(Jar).configureEach {
        archiveBaseName.set("${mod_id}-${project.platform}")
    }

    tasks.named('test') {
        enabled = false
    }

    task publishCurseForge(dependsOn: [':fabric:publishToCurseForge', ':neoforge:publishToCurseForge']) {
        group = "publishing"
    }

    task publishModrinth(dependsOn: [':fabric:modrinth', ':neoforge:modrinth']) {
        group = "publishing"
    }

    task publishMod(dependsOn: ['publish', 'publishCurseForge', 'publishModrinth']) {
        group = "publishing"
    }
}