## Mod
mod_version=4.1.2
mod_id=configuration
mod_name=Configuration
mod_authors=Toma
mod_licence=MIT License
mod_description=Library mod which allows configuration file management and processing
mod_group=dev.toma.configuration

## Minecraft env
java_version=25
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
fabric_minecraft_version=^26.2
vanilla_gradle_version=0.3.2

## Mixin env
mixin_loader=0.7-SNAPSHOT
mixin_version=0.8.6
mixin_min_version=0.8

## Neoforge
neoforge_version=26.2.0.50-beta
neoforge_loader_range=[2,)
neoforge_version_range=[26.2.0.50-beta,26.3)
moddev_version=2.0.141

## Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3
fabric_loom=1.17-SNAPSHOT

## Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
