## Mod
version=3.1.0
mod_id=configuration
mod_name=Configuration
mod_authors=Toma
mod_licence=MIT License
mod_description=Library mod which allows configuration file management and processing
mod_group=dev.toma.configuration

## Minecraft env
java_version=17
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
vanilla_gradle_version=0.2.1-SNAPSHOT

## Mixin env
mixin_loader=0.7-SNAPSHOT
mixin_version=0.8.5
mixin_min_version=0.8

## Forge
forge_version=1.20.1-47.3.11
forge_version_range=[47, 48)
forge_gradle_version=6.0.24

## Fabric
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.16.7
fabric_loom=1.7-SNAPSHOT

## Gradle
root_project=Configuration

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
