## Mod
version=4.0.1
mod_id=configuration
mod_name=Configuration
mod_authors=Toma
mod_licence=MIT License
mod_description=Library mod which allows configuration file management and processing
mod_group=dev.toma.configuration

## Minecraft env
java_version=21
minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.22)
vanilla_gradle_version=0.2.1-SNAPSHOT

## Mixin env
mixin_loader=0.7-SNAPSHOT
mixin_version=0.8.6
mixin_min_version=0.8

## Neoforge
neoforge_version=21.8.4-beta
neoforge_loader_range=[2,)
neoforge_version_range=[21.8.0-beta,22)
neogradle_userdev=7.0.190

## Forge
forge_version=1.21.8-58.0.0
forge_version_range=[58.0, 59)
forge_gradle_version=6.0.36

## Fabric
fabric_version=0.129.0+1.21.8
fabric_loader_version=0.16.14
fabric_loom=1.11-SNAPSHOT

## Gradle
root_project=Configuration

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Publish
cursegradle_plugin_version=1.1.25
modrinth_plugin_version=2.+
compatible_mc_versions=1.21.8
curseforge_project_id=444699
modrinth_project_id=configuration
debug=false
