name: Discord message
on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read changelog
        id: read_changelog
        run: |
          {
            echo "changelog_snippet<<EOF"
            head -n 11 ./CHANGELOG.md
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Trigger webhook
        env:
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          SNIPPET: ${{ steps.read_changelog.outputs.changelog_snippet }}
        run: |
          jq -n \
          --arg snippet "$SNIPPET" \
            '{
              username: "Release bot",
              avatar_url: "https://cdn.discordapp.com/avatars/1308464796831711244/e886df028da3a37ad84b05e3fb0c3b8b.webp?size=32",
              content: "",
              embeds: [
                {
                  title: "Configuration",
                  url: "https://github.com/Toma1O6/Configuration",
                  description: ($snippet),
                  color: 827624,
                  thumbnail: { url: "https://media.forgecdn.net/avatars/1051/443/638581146080795075.png" },
                  fields: [
                    {
                      name: "CurseForge",
                      value: "[Download](<https://www.curseforge.com/minecraft/mc-mods/configuration>)",
                      inline: true
                    },
                    {
                      name: "Modrinth",
                      value: "[Download](<https://modrinth.com/mod/configuration>)",
                      inline: true
                    },
                    {
                      name: "Sources",
                      value: "[GitHub](<https://github.com/Toma1O6/Configuration>)",
                      inline: true
                    },
                    {
                      name: "Support",
                      value: "[Patreon](<https://www.patreon.com/c/tnt_team>)",
                      inline: false
                    },
                    {
                      name: "Report issue",
                      value: "[GitHub](<https://github.com/Toma1O6/Configuration/issues>)",
                      inline: true
                    },
                    {
                      name: "Documentation",
                      value: "[Wiki](<https://github.com/Toma1O6/Configuration/wiki>)",
                      inline: true
                    }
                  ],
                  footer: { text: "CurseForge file may take up to 1 hour to be published" }
                }
              ]
            }' > payload.json
          
          curl "$WEBHOOK" \
            -H "Content-Type: application/json" \
            --data @payload.json