name: 'Publish'
on:
  workflow_dispatch:
  push:
    tags:
      - 'version/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish
        run: ./gradlew publishMod -PCURSEFORGE_TOKEN=${{ secrets.CF_TOKEN }} -PMODRINTH_TOKEN=${{ secrets.MODRINTH_TOKEN }} -PMAVEN_PUBLIC_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USERNAME=${{ secrets.MAVEN_USER }} -PMAVEN_PASSWORD=${{ secrets.MAVEN_PASS }} --no-configuration-cache