name: 'Publish'
on:
  push:
    tags:
      - 'version/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish
        run: ./gradlew publishMod -PCURSEFORGE_TOKEN=${{ secrets.CF_TOKEN }} -PMODRINTH_TOKEN=${{ secrets.MODRINTH_TOKEN }} -PMAVEN_PUBLIC_URL=${{ secrets.MAVEN_URL }} -PMAVEN_USERNAME=${{ secrets.MAVEN_USER }} -PMAVEN_PASSWORD=${{ secrets.MAVEN_PASS }} --no-configuration-cache

      - name: Read changelog
        id: changelog
        uses: Toma1O6/file-read-action@v1
        with:
          file: 'CHANGELOG.md'
          max-lines: '31'
          max-chars: '4096'

      - name: Trigger discord webhook
        env:
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          CHANGELOG: ${{ steps.changelog.outputs.content }}
        run: |
          jq -n \
          --arg snippet "$CHANGELOG" \
            '{
              username: "Release bot",
              avatar_url: "https://cdn.discordapp.com/avatars/1308464796831711244/e886df028da3a37ad84b05e3fb0c3b8b.webp?size=32",
              content: "",
              embeds: [
                {
                  title: "Configuration",
                  url: "https://github.com/Toma1O6/Configuration",
                  description: ($snippet),
                  color: 827624,
                  thumbnail: { url: "https://media.forgecdn.net/avatars/1051/443/638581146080795075.png" },
                  fields: [
                    {
                      name: "CurseForge",
                      value: "[Download](<https://www.curseforge.com/minecraft/mc-mods/configuration>)",
                      inline: true
                    },
                    {
                      name: "Modrinth",
                      value: "[Download](<https://modrinth.com/mod/configuration>)",
                      inline: true
                    },
                    {
                      name: "Sources",
                      value: "[GitHub](<https://github.com/Toma1O6/Configuration>)",
                      inline: true
                    },
                    {
                      name: "Support",
                      value: "[Patreon](<https://www.patreon.com/c/tnt_team>)",
                      inline: false
                    },
                    {
                      name: "Report issue",
                      value: "[GitHub](<https://github.com/Toma1O6/Configuration/issues>)",
                      inline: true
                    },
                    {
                      name: "Documentation",
                      value: "[Wiki](<https://github.com/Toma1O6/Configuration/wiki>)",
                      inline: true
                    }
                  ],
                  footer: { text: "CurseForge file may take up to 1 hour to be published" }
                }
              ]
            }' > payload.json

          curl "$WEBHOOK" \
            -H "Content-Type: application/json" \
            --data @payload.json